### ISSUE TITLE
Add to AUR?

### ISSUE THREAD

**Issue by nickray** [archzfs/zfs-utils#1]
Hi, this is great! Any plans to add it to AUR? As it stands, https://aur.archlinux.org/packages/?O=0&SeB=nd&K=zfs-utils&outdated=&SB=n&SO=a&PP=50&do_Search=Go has way too many options, and the most popular one doesn't build :)

**Comment by minextu** [comment]
They used to be in the AUR, but were removed (see https://github.com/archzfs/archzfs/issues/273).
The zfs-dkms AUR package was just updated anyway and should work again.
